Repository pranaOS/pranaOS, pull requests merged in 2022-01, with the labels that each got.

#117 [libs + ak] updated the include paths
  ak/convert.cpp
  ak/convert.h
  ak/memoperator.cpp
  ak/memoperator.h
  ak/print.cpp
  ak/print.h
  ak/random.h
  ak/string.cpp
  ak/string.h
  bootloader/stage2/math/math.cpp
  external/eclib/vector.h
Labels: enhancement, greatwork

#118 Kernel: core cpu
  kernel/core/memory.h
Labels: enhancement, greatwork

#119 Kernel: core gdtentry header
  kernel/core/gdtentry.h
Labels: enhancement, greatwork

#120 libcore: string header
  ak/string.h
  libs/libcore/version.h
Labels: enhancement, greatwork

#121 Kernel: gdtentry cpp + asm
  kernel/core/cpu.asm
  kernel/core/gdtentry.cpp
Labels: enhancement

#122 Kernel: keyboard support
  kernel/input/keyboard.h
  kernel/input/keyboardmanager.h
Labels: enhancement, greatwork

#123 cpu: poweroff, reboot, tss
  kernel/cpu/poweroff.h
  kernel/cpu/reboot.h
  kernel/cpu/tasksegment.h
Labels: enhancement, greatwork

#124 Kernel: usb driver
  kernel/drivers/usb/defs.h
  kernel/drivers/usb/usbdriver.h
Labels: enhancement, greatwork

#127 Libc: datetime header
  userland/libraries/libc/datetime.cpp
Labels: enhancement, greatwork

#128 Makefile + Grub Config Fille
  grub.cfg
  makefile.config
Labels: enhancement, greatwork

#131 Kernel: [usb] usbcontroller + usbdevice
  kernel/usb/usbcontroller.h
  kernel/usb/usbdevice.h
Labels: enhancement, greatwork, new-feature

#130 kernel: drivers ps2mousedriver header
  kernel/drivers/integrated/ps2mouse.h
Labels: enhancement, greatwork, merged-soon

#133 kernel: cpu vm header
  kernel/cpu/vm.h
Labels: greatwork
